<?php
/**
 * oobyMetrics
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0), a
 * copy of which is available through the world-wide-web at this URL:
 * https://opensource.org/licenses/osl-3.0.php
 *
 * @package    OobyMetrics_OobyMetrics
 * @author     oobyMetrics <code@oobymetrics.com>
 * @copyright  2017 oobyMetrics
 * @license    https://opensource.org/licenses/osl-3.0.php OSL 3.0
 */

if($this->helper('oobymetrics')->isStandaloneIntegrationMethod() && !$this->helper('core/cookie')->isUserNotAllowSaveCookie()) {
    $orderId = Mage::getSingleton('checkout/session')->getLastOrderId();
    $order = Mage::getModel('sales/order')->load($orderId);
    if($order->getId()) {
        ?>
        <!-- oobyMetrics -->
        <script>
        ooby('transaction', {
            'id': '<?php echo $this->jsQuoteEscape($order->getIncrementId()); ?>',
            'revenue': <?php echo (float)$order->getBaseGrandTotal(); ?>,
            'shipping': <?php echo (float)$order->getBaseShippingAmount(); ?>,
            'tax': <?php echo (float)$order->getBaseTaxAmount(); ?>,
            'currency': '<?php echo $this->jsQuoteEscape($order->getOrderCurrencyCode()); ?>',
            'coupon': '<?php echo $this->jsQuoteEscape($order->getCouponCode()); ?>'
        });
        </script>
        <!-- End oobyMetrics -->
        <?php
    }
}